baseURL = 'https://www.petramusik.de/'
languageCode = 'de-de'
title = 'Petra - Musikerin'
theme = 'ananke'
defaultContentLanguage = 'de'
googleAnalytics = ""
enableRobotsTXT = true

# SEO and sitemap settings
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]

[languages]
  [languages.de]
    languageCode = 'de-DE'
    languageDirection = 'ltr'
    languageName = 'Deutsch'
    weight = 1

[params]
  favicon = "/images/favicon/favicon.ico"
  description = "Musikalische Begleitung für Hochzeiten, Beerdigungen und Events in Bempflingen und Umgebung"
  showGallery = true
  mainSections = ["post"]
  
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Über mich"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Simply2"
    url = "/simply2/"
    weight = 3
  [[menu.main]]
    name = "Kontakt"
    url = "/contact/"
    weight = 4
  [[menu.main]]
    name = "Galerie"
    url = "/gallery/"
    weight = 5
  [[menu.main]]
    name = "Impressum"
    url = "/imprint/"
    weight = 6
